name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Check Clasp Version
        run: clasp --version

      - name: Create .clasprc.json from BASE64
        run: echo "${{ secrets.CLASPRC_JSON_B64 }}" | base64 --decode > ~/.clasprc.json

      - name: Validate .clasprc.json
        run: |
          if [ ! -f ~/.clasprc.json ]; then
            echo "ERROR: ~/.clasprc.json does not exist."
            exit 1
          fi
          if [ ! -s ~/.clasprc.json ]; then
            echo "ERROR: ~/.clasprc.json is empty."
            exit 1
          fi
          echo "SUCCESS: ~/.clasprc.json exists and has content."

      - name: Show .clasprc.json contents
        run: |
          echo "===== .clasprc.json ====="
          cat ~/.clasprc.json
          echo "========================="

      - name: Create .clasp.json
        run: |
          echo '{
            "scriptId": "${{ secrets.SCRIPT_ID }}",
            "rootDir": "./src"
          }' > .clasp.json

      - name: Deploy with clasp
        run: clasp push --force